---
title: "머신러닝 - 	[생존모형] 생존분석을 활용한 모형구성"
author: "12조"
date: '2019 11 22 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)
library(survival)
library(survminer)
library(caret)
library(muhaz)
```

## DATA

```{r data}

dat <- readxl::read_xlsx("임상데이터_분석용.xlsx")

```

## Data Preprocessing

```{r}
##성별
#M=1,F=2
dat$성별 <- toupper(dat$성별) %>%
    factor(levels = c("M","F") ,labels = c("M","F"))

##STAGE 
dat$stage<-substring(dat$pStage,1,1) %>%
    as.numeric()

##size : 데이터 형태가 서로달라 width만 정의
size_logic <- ifelse(regexpr("\\d\\.\\d|\\d",dat$Size)<0|
                         is.na(regexpr("\\d\\.\\d|\\d",dat$Size)),F,T)
size_df <- data.frame(size = dat$Size,logic = size_logic)
size_df$width[size_logic] <- regmatches(dat$Size,regexpr("\\d\\.\\d|\\d",dat$Size),invert = F) %>%
    as.numeric()

##Cell type : 조직학적 분류
CT_names = c("ADC","SQC")
for (i in 1:length(CT_names)) {
    CT_ordered_logic <- regexpr(CT_names[i],dat$`Cell type`)>0
    dat$`Cell type`[CT_ordered_logic] <- regmatches(dat$`Cell type`,
                                                    regexpr(CT_names[i],dat$`Cell type`),
                                                    invert = F)
}
dat$`Cell type` <- factor(dat$`Cell type`,
                          levels = CT_names,
                          labels = CT_names)

##Differentiation : 분화,미분화형 
#PD-Poorly/MD-Moderately/WD-Well
DT_names = c("PD","MD","WD")
for (i in 1:length(DT_names)) {
    DT_ordered_logic <- regexpr(DT_names[i],dat$Differentiation)>0
    DT_logic_NA <- ifelse(!is.na(DT_ordered_logic),DT_ordered_logic,F)
    dat$Differentiation[DT_logic_NA] <- regmatches(dat$Differentiation,
                                                    regexpr(DT_names[i],dat$Differentiation),
                                                    invert = F)
}

dat$Differentiation <- factor(dat$Differentiation,
                              labels = DT_names,
                              levels = DT_names)

##림프절 침범여부 Regional lymph nodes (N) of TNM Stage
#N*= 0 , N*>0 = 1
N_stage <- c("N1","N2","N3")
Nodes_logic <- regexpr(N_stage[1],dat$pTNM)>0|
    regexpr(N_stage[2],dat$pTNM)>0|
    regexpr(N_stage[3],dat$pTNM)>0

cLN <- ifelse(Nodes_logic==T,1,0)
##암전이 여부 Distant metastasis (M) of TNM Stage
#0=M0, 1=M1
cMS <- ifelse(regexpr("M1",dat$pTNM)>0,1,0)

#time
dat_time <- data.frame(재발time = as.numeric(dat$재발일자1 - dat$Opdate),
                         TS_FU = as.numeric(dat$`TS F/U` - dat$Opdate),
                         ta_FU = as.numeric(dat$`타과 F/U` - dat$Opdate),
                         ph_FU = as.numeric(dat$전화연락 - dat$Opdate),
                         t.f = dat$재발여부) 
dat_time$max <- apply(dat_time[,2:4],MARGIN = 1,FUN = max,na.rm=T)
dat_time$max[dat_time$max == -Inf] <- NA

dat$time <- ifelse(dat$재발여부==TRUE,
                   dat_time$재발time,
                   dat_time$max)


#새로만들기
varname <- c("성별","Age","stage","Cell type","(+) LN 수","LN 총 수",
             "P 53a","P 53b","ki 67a","ki 67b","Differentiation","재발여부","time")
datset <- subset(dat,select = varname) %>%
    cbind(size_df$width,cLN,cMS) %>%
    na.omit() %>%
    data.frame() %>%
  `colnames<-`(c("Sex","Age","stage","Cell.type","LN수(+)","LN총수",
                 "P.53a","P.53b","ki.67a","ki.67b","Differentiation",
                 "status","time","width","cLN","cMS"))

```
## step

```{r step}
# 1st
asys_1st <- NULL
for (i in c(1:11,14:16)) {
  model <- coxph(Surv(time,status==T)~datset[,i],data = datset)
  table <- rbind(asys_1st,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[1],
                            pvalue = summary(model)$coefficients[5]
                 )
  )
  asys_1st <- table
}
asys_1st



# 2nd (LN수(+):5)
asys_2nd <- NULL
for (i in c(1:4,6:11,14:16)) {
  model <- coxph(Surv(time,status==1)~`LN수(+)`+datset[,i],data = datset)
  table <- rbind(asys_2nd,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[2,1],
                            pvalue = summary(model)$coefficients[2,5]
                 )
  )
  asys_2nd <- table
}
asys_2nd

# 2nd (LN수(+):5,width:14)
asys_3rd <- NULL
for (i in c(1:4,6:11,15:16)) {
  model <- coxph(Surv(time,status==1)~`LN수(+)`+width+datset[,i],data = datset)
  table <- rbind(asys_3rd,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[3,1],
                            pvalue = summary(model)$coefficients[3,5]
                 )
  )
  asys_3rd <- table
}
asys_3rd

# 4th (LN수(+):5,width:14,stage:3)
asys_4th <- NULL
for (i in c(1:2,4,6:11,15:16)) {
  model <- coxph(Surv(time,status==1)~`LN수(+)`+width+stage+datset[,i],data = datset)
  table <- rbind(asys_4th,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[4,1],
                            pvalue = summary(model)$coefficients[4,5]
                 )
  )
  asys_4th <- table
}
asys_4th

# 5th (LN수(+):5,width:14,stage:3,CType;4)
asys_5th <- NULL
for (i in c(1:2,6:11,15:16)) {
  model <- coxph(Surv(time,status==1)~`LN수(+)`+width+stage+Cell.type+datset[,i],data = datset)
  table <- rbind(asys_5th,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[5,1],
                            pvalue = summary(model)$coefficients[5,5]
                 )
  )
  asys_5th <- table
}
asys_5th

# 6th (LN수(+):5,width:14,stage:3,CType;4,ki.67a:9)
asys_6th <- NULL
for (i in c(1:2,6:8,10,11,15:16)) {
  model <- coxph(Surv(time,status==1)~`LN수(+)`+width+stage+Cell.type+ki.67a+datset[,i],data = datset)
  table <- rbind(asys_6th,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[6,1],
                            pvalue = summary(model)$coefficients[6,5]
                 )
  )
  asys_6th <- table
}
asys_6th

ggforest(coxph(Surv(time,status==1)~`LN수(+)`+width+stage+Cell.type+ki.67a,data = datset))


## Age+Sex+Stage 1st
asys_1st <- NULL
for (i in c(4:11,15:16)) {
  model <- coxph(Surv(time,status==T)~Age+Sex+stage+datset[,i],data = datset)
  table <- rbind(asys_1st,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[4,1],
                            pvalue = summary(model)$coefficients[4,5]
                 )
  )
  asys_1st <- table
}
asys_1st

## Age+Sex+Stage(+LN수(+)) 2nd
asys_2nd <- NULL
for (i in c(4,6:11,15:16)) {
  model <- coxph(Surv(time,status==T)~Age+Sex+stage+`LN수(+)`+datset[,i],data = datset)
  table <- rbind(asys_2nd,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[5,1],
                            pvalue = summary(model)$coefficients[5,5]
                 )
  )
  asys_2nd <- table
}
asys_2nd


## Age+Sex+Stage(+LN수(+),Cell.type) 3rd
asys_3rd <- NULL
for (i in c(6:11,15:16)) {
  model <- coxph(Surv(time,status==T)~Age+Sex+stage+`LN수(+)`+Cell.type+datset[,i],data = datset)
  table <- rbind(asys_3rd,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[6,1],
                            pvalue = summary(model)$coefficients[6,5]
                 )
  )
  asys_3rd <- table
}
asys_3rd

## Age+Sex+Stage(+LN수(+),Cell.type,ki.67a) 4th
asys_4th <- NULL
for (i in c(6:8,10:11,15:16)) {
  model <- coxph(Surv(time,status==T)~Age+Sex+stage+`LN수(+)`+Cell.type+ki.67a+datset[,i],data = datset)
  table <- rbind(asys_4th,
                 data.frame(name = colnames(datset)[i],
                            coef = summary(model)$coefficients[7,1],
                            pvalue = summary(model)$coefficients[7,5]
                 )
  )
  asys_4th <- table
}
asys_4th

md_2nd_full <- coxph(Surv(time,status==T)~Age+Sex+stage+`LN수(+)`+Cell.type+ki.67a,data = datset)
summary(md_2nd_full)


```

#PLOT dda

```{r}

#1st model
result_a <- coxph(Surv(time,status==1)~`LN수(+)`+width+stage+Cell.type+ki.67a,data = datset)
median_a <- median(predict(result_a, data=datset))
df_a = cbind(datset[,colnames(datset)=='time'], datset[,colnames(datset)=='status'], predict(result_a, data=datset))
colnames(df_a) <- c('Time','status', 'Predict')
df_a <- data.frame(df_a)
df_a$Predict_cox[(df_a$Predict >= median_a)] <- "High Risk"
df_a$Predict_cox[(df_a$Predict < median_a)] <- "Low Risk"
model_result <- summary(coxph(Surv(Time,status==1) ~ df_a$Predict_cox, data=df_a))
logrank_a <- model_result$logtest[3]

#2nd model based sex+age+stage
result_b <- md_2nd_full
median_b <- median(predict(result_b, data=datset))
df_b = cbind(datset[,colnames(datset)=='time'], datset[,colnames(datset)=='status'], predict(result_b, data=datset))
colnames(df_b) <- c('Time','status', 'Predict')
df_b <- data.frame(df_b)
df_b$Predict_cox[(df_b$Predict >= median_b)] <- "High Risk"
df_b$Predict_cox[(df_b$Predict < median_b)] <- "Low Risk"
model_result_b <- summary(coxph(Surv(Time,status==1) ~ df_b$Predict_cox, data=df_b))
logrank_b <- model_result_b$logtest[3]

# kaplan-meier curve (model)
par(mfrow=c(1,2))

fit1 <- survfit(Surv(Time,status==1) ~ df_a$Predict_cox, data=df_a)
plot(fit1, col = 2:1, lty = 2:3)
legend('topright', legend = c('Low Risk', 'High Risk'), lty = 3:2, col = 1:2)


# kaplan-meier curve (model+rx)

fit2 <- survfit(Surv(time,status==T) ~ df_b$Predict_cox , data=df_b)
plot(fit2, col = 2:1, lty = 2:3)
legend('topright', legend = c('Low Risk', 'High Risk'), lty = 3:2, col = 1:2)


```

## Dif. added

```{r}

fit3 <- survfit(Surv(time,status==T) ~ Differentiation , data=datset)
plot(fit3, col = 3:1, lty = 1:3)
legend('topright', legend = c("PD","MD","WD"), lty = 3:1, col = 1:3)

datset1$Differentiation <- ifelse(datset1$Differentiation == "PD",
                                 0,1)



#1st model
result_a <- coxph(Surv(time,status==1)~`LN수(+)`+width+stage+Cell.type+ki.67a,data = datset1)
median_a <- median(predict(result_a, data=datset1))
df_a = cbind(datset1[,colnames(datset1)=='time'], datset1[,colnames(datset1)=='status'], predict(result_a, data=datset1))
colnames(df_a) <- c('Time','status', 'Predict')
df_a <- data.frame(df_a)
df_a$Predict_cox[(df_a$Predict >= median_a)] <- "High Risk"
df_a$Predict_cox[(df_a$Predict < median_a)] <- "Low Risk"
model_result <- summary(coxph(Surv(Time,status==1) ~ df_a$Predict_cox, data=df_a))
logrank_a <- model_result$logtest[3]

#1st model+dif.
result_b <- coxph(Surv(time,status==1)~`LN수(+)`+width+stage+Cell.type+ki.67a+Differentiation,data = datset1)
median_b <- median(predict(result_b, data=datset1))
df_b = cbind(datset1[,colnames(datset1)=='time'], datset1[,colnames(datset1)=='status'], predict(result_b, data=datset1))
colnames(df_b) <- c('Time','status', 'Predict')
df_b <- data.frame(df_b)
df_b$Predict_cox[(df_b$Predict >= median_b)] <- "High Risk"
df_b$Predict_cox[(df_b$Predict < median_b)] <- "Low Risk"
model_result_b <- summary(coxph(Surv(Time,status==1) ~ df_b$Predict_cox, data=df_b))
logrank_b <- model_result_b$logtest[3]

# kaplan-meier curve (model)
par(mfrow=c(1,2))
fit1 <- survfit(Surv(Time,status==1) ~ df_a$Predict_cox, data=df_a)
plot(fit1, col = 2:1, lty = 2:3)
legend('topright', legend = c('Low Risk', 'High Risk'), lty = 3:2, col = 1:2)

# kaplan-meier curve (model+rx)
fit2 <- survfit(Surv(Time,status==T) ~ df_b$Predict_cox , data=df_b)
plot(fit2, col = 2:1, lty = 2:3)
legend('topright', legend = c('Low Risk', 'High Risk'), lty = 3:2, col = 1:2)

#1st model+dif.
result_c <- coxph(Surv(time,status==1)~Differentiation,data = datset1)
median_c <- median(predict(result_c, data=datset1))
df_c = cbind(datset1[,colnames(datset1)=='time'], datset1[,colnames(datset1)=='status'], predict(result_c, data=datset1))
colnames(df_c) <- c('Time','status', 'Predict')
df_c <- data.frame(df_c)
df_c$Predict_cox[(df_c$Predict > median_c)] <- "High Risk"
df_c$Predict_cox[(df_c$Predict <= median_c)] <- "Low Risk"
model_result_c <- summary(coxph(Surv(Time,status==1) ~ df_c$Predict_cox, data=df_c))
logrank_c <- model_result_c$logtest[3]

# kaplan-meier curve (model+rx)
fit3 <- survfit(Surv(Time,status==T) ~ df_c$Predict_cox , data=df_c)
plot(fit3, col = 2:1, lty = 2:3)
legend('topright', legend = c('Low Risk', 'High Risk'), lty = 3:2, col = 1:2)



```

